apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi
spec:
  selector:
    matchLabels:
      app: flaskapi
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      initContainers:
        - name: wait-for-mysql
          image: willwill/wait-for-it
          env:
            - name: HOST
              value: mysql
            - name: PORT
              value: "3306"
          command: ["sh", "-c", "until nc -z $HOST $PORT; do sleep 1; done"]
      containers:
        - name: flaskapi
          image: tonykurya/flask-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000



---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: LoadBalancer