apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi
spec:
  selector:
    matchLabels:
      app: flaskapi
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: tonykurya/flask-api
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          readinessProbe:
            exec:
              command:
                - sh
                - "-c"
                - >
                  pod_name=$(kubectl get pods -l app=mysql -o jsonpath='{.items[0].metadata.name}')
                  mysql_ready=$(kubectl exec $pod_name -- mysql -h localhost -u root -ppass -e "SELECT 1" 2>/dev/null)
                  if [ "$mysql_ready" ]; then
                    exit 0;
                  else
                    exit 1;
                  fi
            initialDelaySeconds: 10
            periodSeconds: 5


---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: LoadBalancer