apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapi
spec:
  selector:
    matchLabels:
      app: flaskapi
  replicas: 1
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      initContainers:
        - name: init-cont
          image: busybox:1.31
          command: ['sh', '-c', 'echo -e "Checking for the availability of MySQL Server deployment"; while ! nc -z mysql 3306; do sleep 1; printf "-"; done; echo -e "  >> MySQL DB Server has started";']
      containers:
        - name: flaskapi
          image: tonykurya/flask-api
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapi
  type: LoadBalancer